// Caption data types for the extension's YouTube integration.
//
// CaptionEvent mirrors a minimal subset of apps/web/lib/subs/types.ts's
// SSAEvent (start, end, text — all the rest collapses to defaults for
// YouTube tracks).  We vendor instead of importing across workspaces:
// keeps the extension self-contained, drift bounded by the 3-field
// surface.  When the web app's SSAEvent gains a field that 5c/5d need,
// add it here in the same commit.

/** One caption track exposed by YouTube on a watch page.
    Sourced from `ytInitialPlayerResponse.captions.playerCaptionsTracklistRenderer.captionTracks[]`. */
export interface CaptionTrack {
  /** BCP-47 language code as YouTube reports it (e.g. "ja", "zh-Hans", "en"). */
  languageCode: string;
  /** Human-readable name (e.g. "Japanese (auto-generated)"). */
  name: string;
  /** Timed-text endpoint URL.  Append `&fmt=json3` for clean JSON;
      append `&tlang=<lang>` to receive an auto-translated version. */
  baseUrl: string;
  /** "asr" = auto-generated by YouTube's speech recognition.
      "manual" = author-uploaded or community-contributed. */
  kind: "manual" | "asr";
}

/** One caption event from a parsed track.  Times in milliseconds since
    video start.  Mirrors SSAEvent's `start`/`end`/`text` fields. */
export interface CaptionEvent {
  /** Start time in MILLISECONDS since video start (matches SSAEvent.start). */
  start: number;
  /** End time in MILLISECONDS. */
  end: number;
  /** Plain-text caption content with all segs concatenated.  No tags. */
  text: string;
}

/** Stream lifecycle state.  The pill renders directly from this. */
export type StreamStatus =
  | { kind: "idle" }
  | { kind: "detecting" }
  | { kind: "tracking"; targetLang: string; nativeLang: string }
  | { kind: "unsupported"; reason: "no-supported-track" | "no-captions" }
  | { kind: "error"; message: string };

/** Payload of the CaptionStream "change" event — the currently-active
    target + native captions.  Either may be null between events. */
export interface StreamChangeDetail {
  target: CaptionEvent | null;
  native: CaptionEvent | null;
}
