// Caption data types for the extension's YouTube integration.
//
// CaptionEvent mirrors a minimal subset of apps/web/lib/subs/types.ts's
// SSAEvent (start, end, text — all the rest collapses to defaults for
// YouTube tracks).  We vendor instead of importing across workspaces:
// keeps the extension self-contained, drift bounded by the 3-field
// surface.  When the web app's SSAEvent gains a field that 5c/5d need,
// add it here in the same commit.

/** One caption track exposed by a streaming site on a watch page.
    YouTube: `playerCaptionsTracklistRenderer.captionTracks[]`.
    Netflix: a `timedtexttracks[]` entry with a WebVTT downloadable. */
export interface CaptionTrack {
  /** Stable unique identity WITHIN a video's tracklist.  YouTube: vssId
      (e.g. ".en", "a.en").  Netflix: the manifest trackId.  Used for
      React keys, "is this the selected track" matching, and the events
      cache — so same-language variants that share a `languageCode`
      (plain "English" vs "English (CC)") stay distinct.  DO NOT use
      `languageCode` for identity: a video can carry several tracks per
      language, and `baseUrl` is unstable on Netflix (signed URLs rotate
      per manifest fetch). */
  id: string;
  /** BCP-47 language code (e.g. "ja", "zh-Hans", "en"). */
  languageCode: string;
  /** Human-readable name (e.g. "Japanese (auto-generated)", "English (CC)"). */
  name: string;
  /** Timed-text endpoint URL.  YouTube: append `&fmt=json3` / `&tlang=`.
      Netflix: the signed WebVTT URL, fetched as-is. */
  baseUrl: string;
  /** "asr" = auto-generated by YouTube's speech recognition.
      "manual" = author-uploaded / community / (Netflix) all tracks. */
  kind: "manual" | "asr";
  /** True for SDH / closed-caption tracks (Netflix `closedcaptions`).
      These carry non-speech cues ("[ominous music]") that clutter a
      learner view, so auto-pick prefers a plain `subtitles` track when
      one exists — but CC stays user-selectable, and is the fallback when
      it's the only track for a language (JP anime / Thai origin).
      Undefined on platforms without the distinction (treated as standard). */
  isCc?: boolean;
}

/** One caption event from a parsed track.  Times in milliseconds since
    video start.  Mirrors SSAEvent's `start`/`end`/`text` fields. */
export interface CaptionEvent {
  /** Start time in MILLISECONDS since video start (matches SSAEvent.start). */
  start: number;
  /** End time in MILLISECONDS. */
  end: number;
  /** Plain-text caption content with all segs concatenated.  No tags. */
  text: string;
}

/** Stream lifecycle state.  The pill renders directly from this. */
export type StreamStatus =
  | { kind: "idle" }
  | { kind: "detecting" }
  | { kind: "tracking"; targetLang: string; nativeLang: string }
  | { kind: "unsupported"; reason: "no-supported-track" | "no-captions" }
  | { kind: "error"; message: string };

/** Payload of the CaptionStream "change" event — the currently-active
    target + native captions.  Either may be null between events. */
export interface StreamChangeDetail {
  target: CaptionEvent | null;
  native: CaptionEvent | null;
}
