// Caption data types for the extension's YouTube integration.
//
// CaptionEvent mirrors a minimal subset of apps/web/lib/subs/types.ts's
// SSAEvent (start, end, text — all the rest collapses to defaults for
// YouTube tracks).  We vendor instead of importing across workspaces:
// keeps the extension self-contained, drift bounded by the 3-field
// surface.  When the web app's SSAEvent gains a field that 5c/5d need,
// add it here in the same commit.

/** One caption track exposed by a streaming site on a watch page.
    YouTube: `playerCaptionsTracklistRenderer.captionTracks[]`.
    Netflix: a `timedtexttracks[]` entry with a WebVTT downloadable. */
export interface CaptionTrack {
  /** Stable unique identity WITHIN a video's tracklist.  YouTube: vssId
      (e.g. ".en", "a.en").  Netflix: the manifest trackId.  Used for
      React keys, "is this the selected track" matching, and the events
      cache — so same-language variants that share a `languageCode`
      (plain "English" vs "English (CC)") stay distinct.  DO NOT use
      `languageCode` for identity: a video can carry several tracks per
      language, and `baseUrl` is unstable on Netflix (signed URLs rotate
      per manifest fetch). */
  id: string;
  /** BCP-47 language code (e.g. "ja", "zh-Hans", "en"). */
  languageCode: string;
  /** Human-readable name (e.g. "Japanese (auto-generated)", "English (CC)"). */
  name: string;
  /** Timed-text endpoint URL.  YouTube: append `&fmt=json3` / `&tlang=`.
      Netflix: the signed WebVTT URL, fetched as-is. */
  baseUrl: string;
  /** "asr" = auto-generated by YouTube's speech recognition.
      "manual" = author-uploaded / community / (Netflix) all tracks. */
  kind: "manual" | "asr";
  /** True for SDH / closed-caption tracks (Netflix `closedcaptions`).
      These carry non-speech cues ("[ominous music]") that clutter a
      learner view, so auto-pick prefers a plain `subtitles` track when
      one exists — but CC stays user-selectable, and is the fallback when
      it's the only track for a language (JP anime / Thai origin).
      Undefined on platforms without the distinction (treated as standard). */
  isCc?: boolean;
  /** Base BCP-47 code of the video's PRIMARY/original audio language, when
      the platform exposes it.  A per-VIDEO property (identical on every
      track of a tracklist), carried here so auto-pick can default the Top
      (foreign) layer to the language actually being spoken — e.g. Japanese
      on a Japanese-audio anime rather than whichever track happens to sort
      first.  Netflix: derived from the manifest's audio tracks.  Undefined
      when the platform doesn't expose it (e.g. YouTube today) → auto-pick
      falls back to its tier ordering. */
  audioLangCode?: string;
}

/** Writing orientation of a cue, resolved from the source's region /
    cue-settings.  `horizontal` = normal left-to-right, top-to-bottom
    (`lrtb`).  `vertical-rl` = Japanese tategaki (`tbrl`: columns run
    top-to-bottom, advancing right-to-left).  `vertical-lr` = `tblr`. */
export type WritingMode = "horizontal" | "vertical-rl" | "vertical-lr";

/** Source-derived layout for a cue — where it sits on the frame and how
    it's oriented.  Extracted non-destructively at parse time (Prime TTML
    regions today; Netflix VTT cue-settings next) so Loom can REPRODUCE a
    vertical / positioned cue faithfully instead of flattening every cue to
    one bottom slot.  All positional fields are best-effort: a coarse 3×3
    zone (always resolvable) plus the precise region box when the source
    defines `tts:origin`/`tts:extent`. */
export interface CueLayout {
  writingMode: WritingMode;
  /** Coarse vertical zone of the cue's region. */
  block: "top" | "middle" | "bottom";
  /** Coarse horizontal zone of the cue's region. */
  inline: "left" | "center" | "right";
  /** Text alignment within the cue, when the source specifies it. */
  textAlign?: "start" | "center" | "end";
  /** Region top-left as a fraction [0..1] of the frame, when the source
      region defines `tts:origin`.  Overlay prefers this over `block`/
      `inline` when present. */
  origin?: { x: number; y: number };
  /** Region size as a fraction [0..1] of the frame, from `tts:extent`. */
  extent?: { w: number; h: number };
  /** Raw source region id (e.g. "横下"), for debugging + future precise
      placement. */
  regionId?: string;
}

/** One caption event from a parsed track.  Times in milliseconds since
    video start.  Mirrors SSAEvent's `start`/`end`/`text` fields. */
export interface CaptionEvent {
  /** Start time in MILLISECONDS since video start (matches SSAEvent.start). */
  start: number;
  /** End time in MILLISECONDS. */
  end: number;
  /** Plain-text caption content with all segs concatenated.  No tags. */
  text: string;
  /** Source-derived position + orientation, when the track carries it
      (Prime TTML regions; Netflix VTT cue-settings).  Undefined = no
      positional data → the overlay uses its default placement (the
      pre-existing behavior).  Preserving this is what lets Loom render
      vertical / positioned cues faithfully rather than flattening them. */
  layout?: CueLayout;
}

/** Stream lifecycle state.  The pill renders directly from this. */
export type StreamStatus =
  | { kind: "idle" }
  | { kind: "detecting" }
  | { kind: "tracking"; targetLang: string; nativeLang: string }
  | { kind: "unsupported"; reason: "no-supported-track" | "no-captions" }
  | { kind: "error"; message: string };

/** Payload of the CaptionStream "change" event — the currently-active
    target + native captions.  Either may be null between events. */
export interface StreamChangeDetail {
  target: CaptionEvent | null;
  native: CaptionEvent | null;
}
