/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload File */
        post: operations["upload_file_files_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/by-path": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register File By Path */
        post: operations["register_file_by_path_files_by_path_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{file_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download File */
        get: operations["download_file_files__file_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/language/config/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Language Config
         * @description Wire-safe view of ``loom_core.styles.get_lang_config()``.
         *
         *     Drops the callable fields (``romanize_func``, ``annotation_func``, etc.)
         *     which can't cross the wire. The engine reconstructs them server-side
         *     from ``code`` + ``phonetic_system`` on each request that needs them.
         */
        get: operations["language_config_language_config__code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/romanize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Romanize */
        post: operations["romanize_romanize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/romanize/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Romanize Batch */
        post: operations["romanize_batch_romanize_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/annotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Annotate */
        post: operations["annotate_annotate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/annotate/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Annotate Batch */
        post: operations["annotate_batch_annotate_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/generate/ass": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Ass */
        post: operations["generate_ass_generate_ass_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/generate/pgs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Pgs */
        post: operations["generate_pgs_generate_pgs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/generate/suggest-filename": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Suggest Filename */
        post: operations["suggest_filename_generate_suggest_filename_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/video/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Scan Video
         * @description Scan an uploaded video for subtitle tracks + metadata.
         *
         *     Text tracks are extracted to the storage tempdir and registered with
         *     new file IDs that the client can use in /generate/ass, /preview, etc.
         *     Image-based tracks (PGS, VobSub) are surfaced with ``selectable=False``
         *     and ``file_id=None``; they need OCR before they can be used as text.
         */
        post: operations["scan_video_video_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subs/detect-language": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Detect Subtitle Language */
        post: operations["detect_subtitle_language_subs_detect_language_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subs/detect-styles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Detect Subtitle Styles
         * @description Returns the named-style breakdown for an ASS/SSA file with multiple
         *     styles. SRT files and single-style ASS files return ``styles=None`` —
         *     they have no meaningful style breakdown.
         */
        post: operations["detect_subtitle_styles_subs_detect_styles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/align": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compute Align */
        post: operations["compute_align_align_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Render Preview
         * @description Render the composite preview HTML at a single timestamp.
         *
         *     Mirrors the Streamlit preview wiring: computes annotation spans when
         *     the Annotation layer is enabled, runs the Japanese ``spans_to_romaji``
         *     pipeline with the user's ``long_vowel_mode`` (reusing spans when
         *     annotation is already computed), and — when ``video_file_id`` is
         *     supplied — inlines a cached frame screenshot as the preview
         *     background.
         */
        post: operations["render_preview_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/styles/fonts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fonts */
        get: operations["fonts_styles_fonts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/styles/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Presets
         * @description Catalogue of color presets applicable to ``lang``.
         *
         *     Universal presets (``languages=None``) are always included. Language-scoped
         *     presets are included when their scope matches ``lang`` via prefix.
         *     Empty ``lang`` returns universal presets only.
         */
        get: operations["presets_styles_presets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mux": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Mux */
        post: operations["start_mux_mux_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/corpus/capture": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Corpus Capture */
        post: operations["corpus_capture_corpus_capture_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/define/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Define Capabilities
         * @description What the dictionary can answer right now.  The extension reads this at
         *     runtime to decide which tracks get clickable words and which gloss languages
         *     to offer — so a NEW dictionary is a pure server change, no extension update.
         *     A source language is included only if it has both data AND a tokenizer.
         */
        get: operations["define_capabilities_define_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/define/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Define Batch */
        post: operations["define_batch_define_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AlignRequest
         * @description Compute the auto-alignment offset between two same-language subtitle tracks.
         *
         *     Sign convention matches ``loom_core.subs.utils.compute_subtitle_offset``:
         *     positive offset means the reference is earlier than the target (shift
         *     reference-source tracks later by ``offset_seconds`` to align).
         */
        AlignRequest: {
            /** Reference File Id */
            reference_file_id: string;
            /** Target File Id */
            target_file_id: string;
        };
        /** AlignResponse */
        AlignResponse: {
            /** Offset Seconds */
            offset_seconds: number;
            /** Warning */
            warning?: string | null;
        };
        /**
         * AnnotateBatchItem
         * @description One result entry — same shape as the spans+html fields of
         *     AnnotateResponse, minus the per-call metadata (lang_code,
         *     annotation_system_name, render_mode) which is constant across the
         *     batch and lives at the response root.
         */
        AnnotateBatchItem: {
            /** Spans */
            spans: components["schemas"]["AnnotateSpan"][];
            /** Tokens */
            tokens?: components["schemas"]["AnnotateToken"][];
            /** Html */
            html: string;
        };
        /** AnnotateBatchRequest */
        AnnotateBatchRequest: {
            /**
             * Texts
             * @description UTF-8 source texts to annotate.  All texts share the lang/phonetic_system specified at the request level.  Hard caps: ≤2000 entries, each ≤5000 chars.
             */
            texts: string[];
            /**
             * Lang Code
             * @description See POST /annotate.
             */
            lang_code: string;
            /**
             * Phonetic System
             * @description See POST /annotate.
             */
            phonetic_system?: string | null;
            /**
             * Render Mode
             * @description See POST /annotate.
             */
            render_mode?: string | null;
            /**
             * Opt In Training
             * @description See POST /annotate.
             * @default false
             */
            opt_in_training: boolean;
        };
        /** AnnotateBatchResponse */
        AnnotateBatchResponse: {
            /**
             * Results
             * @description One entry per input text, same order as the request.  Empty/oversized texts produce {spans: [], html: ''} instead of being dropped, so positional alignment with the request is preserved.
             */
            results: components["schemas"]["AnnotateBatchItem"][];
            /** Lang Code */
            lang_code: string;
            /** Annotation System Name */
            annotation_system_name: string;
            /** Render Mode */
            render_mode: string;
        };
        /** AnnotateRequest */
        AnnotateRequest: {
            /**
             * Text
             * @description UTF-8 source text to annotate (≤5000 chars).
             */
            text: string;
            /**
             * Lang Code
             * @description BCP-47 language tag (ja, zh-Hans, zh-Hant, yue, ko, th, hi, ...).
             */
            lang_code: string;
            /**
             * Phonetic System
             * @description Per-language phonetic-system override.  Same values as POST /romanize.  Drives which annotation system is selected for languages that support multiple (Mandarin pinyin vs zhuyin, Cantonese jyutping, Thai paiboon/rtgs/ipa, etc.).
             */
            phonetic_system?: string | null;
            /**
             * Render Mode
             * @description How to render the resulting HTML: 'ruby' (default for CJK; <ruby>+<rt>), 'interlinear' (two-row inline-block stack; better for long alphabetic readings), or 'inline' (parenthetical fallback: 'base(reading)').  When omitted, falls back to the language's default annotation_render_mode.
             */
            render_mode?: string | null;
            /**
             * Opt In Training
             * @description See POST /romanize.  No-op until the OCR archival pipeline lands (Step 5+).
             * @default false
             */
            opt_in_training: boolean;
        };
        /** AnnotateResponse */
        AnnotateResponse: {
            /** Spans */
            spans: components["schemas"]["AnnotateSpan"][];
            /** Tokens */
            tokens?: components["schemas"]["AnnotateToken"][];
            /** Html */
            html: string;
            /** Render Mode */
            render_mode: string;
            /** Annotation System Name */
            annotation_system_name: string;
            /** Lang Code */
            lang_code: string;
        };
        /** AnnotateSpan */
        AnnotateSpan: {
            /** Base */
            base: string;
            /** Reading */
            reading?: string | null;
        };
        /**
         * AnnotateToken
         * @description Word-level grouping over `spans` for per-word vocab lookup
         *     (VOCAB_LOOKUP.md Phase 0).  `spans[start:start+length]` compose the word.
         *     Only Japanese + Chinese populate this; other languages return [].
         */
        AnnotateToken: {
            /**
             * Word
             * @description The clickable word surface form.
             */
            word: string;
            /**
             * Lemma
             * @description Dictionary form for /define (JA); null → use word.
             */
            lemma?: string | null;
            /**
             * Pos
             * @description Part-of-speech tags (JA); [] for ZH.
             */
            pos?: string[];
            /**
             * Reading
             * @description Contextual kana reading of the surface (JA; topic particle は → わ). null → the card falls back to the dictionary reading.
             */
            reading?: string | null;
            /**
             * Start
             * @description Index into `spans` where this word begins.
             */
            start: number;
            /**
             * Length
             * @description Number of spans this word covers.
             */
            length: number;
        };
        /** AnnotationLayerStyle */
        AnnotationLayerStyle: {
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
            /**
             * Fontname
             * @default Noto Sans
             */
            fontname: string;
            /**
             * Fontsize
             * @default 22
             */
            fontsize: number;
            /**
             * Bold
             * @default false
             */
            bold: boolean;
            /**
             * Italic
             * @default false
             */
            italic: boolean;
            /**
             * Primarycolor
             * @default #FFFFFF
             */
            primarycolor: string;
            /**
             * Primary Opacity
             * @default 100
             */
            primary_opacity: number;
            /**
             * Outlinecolor
             * @default #000000
             */
            outlinecolor: string;
            /**
             * Outline Opacity
             * @default 100
             */
            outline_opacity: number;
            /**
             * Backcolor
             * @default #000000
             */
            backcolor: string;
            /**
             * Back Opacity
             * @default 0
             */
            back_opacity: number;
            /**
             * Outline Enabled
             * @default true
             */
            outline_enabled: boolean;
            /**
             * Outline
             * @default 1
             */
            outline: number;
            /**
             * Shadow Enabled
             * @default false
             */
            shadow_enabled: boolean;
            /**
             * Shadow
             * @default 1.5
             */
            shadow: number;
            /**
             * Background Enabled
             * @default false
             */
            background_enabled: boolean;
            /**
             * Glow Enabled
             * @default false
             */
            glow_enabled: boolean;
            /**
             * Glow Radius
             * @default 5
             */
            glow_radius: number;
            /**
             * Glow Color Hex
             * @default #FFFF00
             */
            glow_color_hex: string;
            /**
             * Alignment
             * @default 8
             */
            alignment: number;
            /**
             * Marginl
             * @default 10
             */
            marginl: number;
            /**
             * Marginr
             * @default 10
             */
            marginr: number;
            /**
             * Marginv
             * @default 10
             */
            marginv: number;
            /** Phonetic System */
            phonetic_system?: ("pinyin" | "zhuyin" | "jyutping" | "rtgs" | "paiboon" | "ipa") | null;
        };
        /**
         * AudioTrackInfo
         * @description One audio track from the scanned video, surfaced for the mux UI's
         *     "default audio" selector.
         *
         *     ``audio_index`` is the 0-based index *among audio streams only* —
         *     this is what ffmpeg's ``-disposition:a:N`` expects, and what
         *     ``mkv_handler.merge_subs_to_mkv(default_audio_index=...)`` consumes.
         */
        AudioTrackInfo: {
            /** Audio Index */
            audio_index: number;
            /** Codec */
            codec?: string | null;
            /** Channels */
            channels?: number | null;
            /** Lang Code */
            lang_code?: string | null;
            /** Title */
            title?: string | null;
        };
        /** Body_upload_file_files_post */
        Body_upload_file_files_post: {
            /** File */
            file: string;
        };
        /** BottomLayerStyle */
        BottomLayerStyle: {
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Fontname
             * @default Georgia
             */
            fontname: string;
            /**
             * Fontsize
             * @default 48
             */
            fontsize: number;
            /**
             * Bold
             * @default false
             */
            bold: boolean;
            /**
             * Italic
             * @default false
             */
            italic: boolean;
            /**
             * Primarycolor
             * @default #FFFFFF
             */
            primarycolor: string;
            /**
             * Primary Opacity
             * @default 100
             */
            primary_opacity: number;
            /**
             * Outlinecolor
             * @default #000000
             */
            outlinecolor: string;
            /**
             * Outline Opacity
             * @default 100
             */
            outline_opacity: number;
            /**
             * Backcolor
             * @default #000000
             */
            backcolor: string;
            /**
             * Back Opacity
             * @default 0
             */
            back_opacity: number;
            /**
             * Outline Enabled
             * @default true
             */
            outline_enabled: boolean;
            /**
             * Outline
             * @default 3
             */
            outline: number;
            /**
             * Shadow Enabled
             * @default false
             */
            shadow_enabled: boolean;
            /**
             * Shadow
             * @default 1.5
             */
            shadow: number;
            /**
             * Background Enabled
             * @default false
             */
            background_enabled: boolean;
            /**
             * Glow Enabled
             * @default false
             */
            glow_enabled: boolean;
            /**
             * Glow Radius
             * @default 5
             */
            glow_radius: number;
            /**
             * Glow Color Hex
             * @default #FFFF00
             */
            glow_color_hex: string;
            /**
             * Alignment
             * @default 2
             */
            alignment: number;
            /**
             * Marginl
             * @default 10
             */
            marginl: number;
            /**
             * Marginr
             * @default 10
             */
            marginr: number;
            /**
             * Marginv
             * @default 40
             */
            marginv: number;
        };
        /** CaptureLine */
        CaptureLine: {
            /**
             * Seq
             * @description 0-based position in the track's event order.
             */
            seq: number;
            /**
             * Start Ms
             * @description Event start, milliseconds.
             */
            start_ms?: number | null;
            /**
             * End Ms
             * @description Event end, milliseconds.
             */
            end_ms?: number | null;
            /** Text */
            text: string;
            /**
             * Style
             * @description ASS style name for this event (file sources: web upload / desktop / player).  Streaming platforms have no style visibility and omit it.
             */
            style?: string | null;
        };
        /** CorpusCaptureRequest */
        CorpusCaptureRequest: {
            /**
             * Opt In Training
             * @description Must be true for anything to be stored.  The extension sends this from the user's opt-in setting; false → 200 stored=false.
             * @default false
             */
            opt_in_training: boolean;
            /**
             * Platform
             * @description youtube | netflix | iqiyi | wetv | ...
             */
            platform: string;
            /**
             * Media Id
             * @description Platform-native media id (videoId / movieId / ...).
             */
            media_id: string;
            /**
             * Title
             * @description Best-effort human-readable title.
             */
            title?: string | null;
            /**
             * Origin Lang
             * @description Media's origin/audio language, if known.
             */
            origin_lang?: string | null;
            /**
             * Track Id
             * @description Platform-native track id (vssId / trackId / ...).
             */
            track_id: string;
            /**
             * Track Lang
             * @description BCP-47 language tag of the captured track.
             */
            track_lang: string;
            /**
             * Is Cc
             * @description True for closed-captions/SDH tracks.
             * @default false
             */
            is_cc: boolean;
            /**
             * Track Kind
             * @description e.g. manual | asr.
             */
            track_kind?: string | null;
            /**
             * Lines
             * @description Full ordered timed event list.
             */
            lines: components["schemas"]["CaptureLine"][];
            /**
             * Styles
             * @description Style DEFINITIONS for the style names referenced by lines — an opaque JSON map {style_name: {fontname, fontsize, colors, ...}} exactly as the client parsed it.  File sources only; the (text, style, language) tuples for Step 6 OCR training.
             */
            styles?: {
                [key: string]: unknown;
            } | null;
        };
        /** CorpusCaptureResponse */
        CorpusCaptureResponse: {
            /** Stored */
            stored: boolean;
            /**
             * Deduped
             * @description True when this exact track content was already captured.
             * @default false
             */
            deduped: boolean;
            /**
             * Lines
             * @description Line rows written (0 on no-op/dedup).
             * @default 0
             */
            lines: number;
            /**
             * Reason
             * @description Human-readable no-op explanation when stored=false.
             * @default
             */
            reason: string;
        };
        /** DefineCapabilities */
        DefineCapabilities: {
            /**
             * Source Langs
             * @description Languages with a dictionary AND a word tokenizer — the video-track languages Loom can offer per-word lookup for.
             */
            source_langs: string[];
            /**
             * Gloss Langs
             * @description Languages definitions can be written in (English always).
             */
            gloss_langs: string[];
            /**
             * Gloss Langs By Source
             * @description Per source language, which gloss languages actually have entries — drives the client's per-video 'Dictionary language' picker so it offers only languages a definition can really be written in.
             */
            gloss_langs_by_source?: {
                [key: string]: string[];
            };
            /**
             * Version
             * @description Wire-format version of this response.
             */
            version: number;
        };
        /**
         * DefinePart
         * @description One component of a decomposed word — a Chinese sub-word (jieba grouped
         *     number+measure-word etc.) or a Japanese honorific peeled off a name.
         */
        DefinePart: {
            /** Word */
            word: string;
            /** Reading */
            reading?: string | null;
            /**
             * Romaji
             * @description Hepburn (macrons), Japanese only.
             */
            romaji?: string | null;
            /**
             * Romaji Alt
             * @description Hepburn (doubled vowels), Japanese only.
             */
            romaji_alt?: string | null;
            /** Senses */
            senses?: components["schemas"]["DefineSense"][];
        };
        /** DefineRequest */
        DefineRequest: {
            /**
             * Lang
             * @description Base language of the words: 'ja' | 'zh'.
             */
            lang: string;
            /**
             * Words
             * @description Primary keys to define (from the annotate tokens) — usually the lemma.  Each is tried first, then its `alt_keys`; the first that hits wins.  Echoed back verbatim as the result `word`.
             */
            words: string[];
            /**
             * Alt Keys
             * @description Optional per-word fallback keys, aligned to `words` by index — e.g. the token's surface form so 黒曜石 resolves when MeCab's lemma (黒曜) doesn't.  Tried in order after the primary key.
             */
            alt_keys?: string[][] | null;
            /**
             * Readings
             * @description Optional per-word contextual kana readings, aligned to `words` — the reading the card DISPLAYS (e.g. は→わ, the inflected 見た).  For Japanese, the returned `romaji`/`romaji_alt` are computed from this (falling back to the dictionary reading) so the Hepburn matches the shown furigana.
             */
            readings?: string[] | null;
            /**
             * Gloss Lang
             * @description Language the definitions should be written in (the user's language; usually the browser locale).  Falls back to English per-word when a word has no gloss in this language.  Defaults to English.
             */
            gloss_lang?: string | null;
            /**
             * Surfaces
             * @description Optional per-word INFLECTED surface forms, aligned to `words` — the word as it appears in the caption (食べさせられた) vs its dictionary lemma (食べる).  Used to compute the `grammar` breakdown; when absent the primary key is analyzed instead.
             */
            surfaces?: string[] | null;
            /**
             * Surface Continuations
             * @description Optional per-word continuation text, aligned to `words` — the lead of the NEXT subtitle cue, for a predicate split across events (利用し | てタム… → 利用して).  Stitched onto `surfaces` for the grammar breakdown so a split verb recovers its true inflection.  Japanese only; harmless when the word is already complete.
             */
            surface_continuations?: string[] | null;
        };
        /** DefineResponse */
        DefineResponse: {
            /** Lang */
            lang: string;
            /** Results */
            results: components["schemas"]["DefineResult"][];
        };
        /** DefineResult */
        DefineResult: {
            /**
             * Word
             * @description The requested word, echoed back.
             */
            word: string;
            /**
             * Found
             * @description True iff the word itself has a direct dictionary entry.
             */
            found: boolean;
            /**
             * Reading
             * @description Reading/pronunciation (kana / numbered pinyin).
             */
            reading?: string | null;
            /**
             * Romaji
             * @description Hepburn romanization with macrons (Tōkyō), Japanese only.
             */
            romaji?: string | null;
            /**
             * Romaji Alt
             * @description Hepburn with doubled long vowels (Toukyou), Japanese only; omitted/equal to `romaji` when there's no long vowel.
             */
            romaji_alt?: string | null;
            /** Senses */
            senses?: components["schemas"]["DefineSense"][];
            /**
             * Sources
             * @description e.g. ['jmdict'] / ['cc-cedict'].
             */
            sources?: string[];
            /**
             * Parts
             * @description Decomposition breakdown when `found` is false but the word splits into known sub-words (e.g. 一顶 → 一 + 顶, or 玉葉様 → 様).  Empty on a direct hit.
             */
            parts?: components["schemas"]["DefinePart"][];
            /** @description Grammar breakdown of the inflected SURFACE form (Japanese): its dictionary form + the ordered inflection features (causative / passive / past …).  Present only when the surface actually carries inflection to explain; null for a plain dictionary form or a language with no grammar analyzer. */
            grammar?: components["schemas"]["GrammarBreakdown"] | null;
        };
        /** DefineSense */
        DefineSense: {
            /**
             * Gloss
             * @description Glosses for this sense (synonyms kept as given).
             */
            gloss: string[];
            /**
             * Pos
             * @description Part-of-speech tags (JMdict; empty for CC-CEDICT).
             */
            pos?: string[];
            /**
             * Misc
             * @description Misc/usage tags (e.g. 'usually kana').
             */
            misc?: string[];
        };
        /** DetectLanguageResponse */
        DetectLanguageResponse: {
            /** Code */
            code: string | null;
            /** Name */
            name: string | null;
        };
        /** DetectStylesResponse */
        DetectStylesResponse: {
            /** Styles */
            styles: components["schemas"]["StyleInfo"][] | null;
        };
        /** FileIdRequest */
        FileIdRequest: {
            /** File Id */
            file_id: string;
        };
        /** FontList */
        FontList: {
            /** All */
            all: string[];
            /** Cjk */
            cjk: string[];
        };
        /**
         * GenerateAssRequest
         * @description Client → server request for ASS generation.
         *
         *     File handles cross the wire as IDs (returned by POST /files), not paths.
         *     The server resolves IDs → on-disk paths just before calling the engine.
         *
         *     ``opt_in_training``: when true, the server is permitted to archive
         *     ``(input_text, style_config, output, lang_code)`` for OCR training data.
         *     Defaults to false. No archival code wired in step 2c — the field is
         *     baked into the contract so consumers don't need to upgrade their
         *     request shapes when archival turns on later.
         */
        GenerateAssRequest: {
            /** Native File Id */
            native_file_id: string;
            /** Target File Id */
            target_file_id: string;
            /** Target Lang Code */
            target_lang_code: string;
            styles: components["schemas"]["StyleConfig"];
            /**
             * @default {
             *       "bottom_ms": 0,
             *       "top_ms": 0
             *     }
             */
            offsets: components["schemas"]["TimingOffsets"];
            /**
             * @default {
             *       "width": 1920,
             *       "height": 1080
             *     }
             */
            source_resolution: components["schemas"]["Resolution"];
            output_resolution?: components["schemas"]["Resolution"] | null;
            /**
             * Include Annotations
             * @default false
             */
            include_annotations: boolean;
            /**
             * Opt In Training
             * @default false
             */
            opt_in_training: boolean;
        };
        /** GenerateAssResponse */
        GenerateAssResponse: {
            /** File Id */
            file_id: string;
        };
        /**
         * GeneratePgsRequest
         * @description Client → server request for PGS generation. Async — returns a job ID.
         *
         *     PGS rasterization takes 30s–10min depending on event count and
         *     canvas resolution. Poll GET /jobs/{id} for progress. When ``state``
         *     transitions to ``completed``, ``result_file_id`` resolves to the
         *     generated .sup via GET /files/{id}.
         */
        GeneratePgsRequest: {
            /** Native File Id */
            native_file_id: string;
            /** Target File Id */
            target_file_id: string;
            /** Target Lang Code */
            target_lang_code: string;
            styles: components["schemas"]["StyleConfig"];
            /**
             * @default {
             *       "bottom_ms": 0,
             *       "top_ms": 0
             *     }
             */
            offsets: components["schemas"]["TimingOffsets"];
            /**
             * @default {
             *       "width": 1920,
             *       "height": 1080
             *     }
             */
            source_resolution: components["schemas"]["Resolution"];
            output_resolution?: components["schemas"]["Resolution"] | null;
            /**
             * Opt In Training
             * @default false
             */
            opt_in_training: boolean;
        };
        /**
         * GrammarBreakdown
         * @description A word's dictionary form + the grammar features stacked onto it,
         *     inner→outer (食べる → causative → passive → past).
         */
        GrammarBreakdown: {
            /**
             * Dict Form
             * @description Dictionary/plain form of the word.
             */
            dict_form: string;
            /** Features */
            features?: components["schemas"]["GrammarFeature"][];
        };
        /**
         * GrammarFeature
         * @description One step in a word's inflection chain (Japanese).
         */
        GrammarFeature: {
            /**
             * Code
             * @description Stable feature id for client localization, e.g. 'causative'.
             */
            code: string;
            /**
             * Display
             * @description English label, shown when the client has no localization for `code`.
             */
            display: string;
            /**
             * Surface
             * @description The morpheme(s) carrying this feature, e.g. 'させ'.
             * @default
             */
            surface: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobAccepted */
        JobAccepted: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "ass" | "pgs" | "mux";
        };
        /** JobStatus */
        JobStatus: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "ass" | "pgs" | "mux";
            /**
             * State
             * @enum {string}
             */
            state: "pending" | "running" | "completed" | "failed";
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /** Phase */
            phase?: string | null;
            /** Result File Id */
            result_file_id?: string | null;
            /** Error */
            error?: string | null;
        };
        /**
         * LanguageMetadata
         * @description Serializable subset of ``styles.get_lang_config()``.
         *
         *     Drops the callable fields (``romanize_func``, ``annotation_func``,
         *     ``resolve_spans_func``, ``spans_to_romaji_func``, ``word_boundary_func``)
         *     which can't cross the wire. The engine reconstructs them server-side
         *     from ``code`` + ``phonetic_system``.
         */
        LanguageMetadata: {
            /** Code */
            code: string;
            /** Chinese Variant */
            chinese_variant?: ("zh-Hans" | "zh-Hant" | "yue") | null;
            /** Phonetic System */
            phonetic_system?: ("pinyin" | "zhuyin" | "jyutping" | "rtgs" | "paiboon" | "ipa") | null;
            /** Has Phonetic Layer */
            has_phonetic_layer: boolean;
            /** Supports Ass Annotation */
            supports_ass_annotation: boolean;
            /** Annotation Default Enabled */
            annotation_default_enabled: boolean;
            /**
             * Annotation System Name
             * @default Annotation
             */
            annotation_system_name: string;
            /**
             * Annotation Render Mode
             * @default ruby
             * @enum {string}
             */
            annotation_render_mode: "ruby" | "interlinear" | "inline";
            /**
             * Annotation Font Ratio
             * @default 0.5
             */
            annotation_font_ratio: number;
            /**
             * Romanization Name
             * @default N/A
             */
            romanization_name: string;
            /**
             * Romanization Confidence
             * @default none
             * @enum {string}
             */
            romanization_confidence: "very_high" | "high" | "good" | "moderate" | "low" | "none";
            /**
             * Default Font
             * @default Arial
             */
            default_font: string;
            /**
             * Rtl
             * @default false
             */
            rtl: boolean;
        };
        /** LayerColors */
        LayerColors: {
            /** Color */
            color: string;
            /**
             * Opacity
             * @default 100
             */
            opacity: number;
            /**
             * Outline Color
             * @default #000000
             */
            outline_color: string;
            /**
             * Outline Opacity
             * @default 90
             */
            outline_opacity: number;
            /** Glow Color */
            glow_color?: string | null;
            /** Glow Opacity */
            glow_opacity?: number | null;
        };
        /** MuxRequest */
        MuxRequest: {
            /** Video File Id */
            video_file_id: string;
            /** Ass File Id */
            ass_file_id?: string | null;
            /** Sup File Id */
            sup_file_id?: string | null;
            /** Output Path */
            output_path: string;
            /** Target Lang Code */
            target_lang_code?: string | null;
            /** Native Lang Code */
            native_lang_code?: string | null;
            /** Phonetic System */
            phonetic_system?: ("pinyin" | "zhuyin" | "jyutping" | "rtgs" | "paiboon" | "ipa") | null;
            /**
             * Annotation Enabled
             * @default false
             */
            annotation_enabled: boolean;
            /**
             * Keep Existing Subs
             * @default true
             */
            keep_existing_subs: boolean;
            /**
             * Keep Attachments
             * @default true
             */
            keep_attachments: boolean;
            /** Default Audio Index */
            default_audio_index?: number | null;
        };
        /** Preset */
        Preset: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Description */
            description: string;
            /** Group */
            group: string;
            /** Layers */
            layers: {
                [key: string]: components["schemas"]["LayerColors"];
            };
            /** Languages */
            languages?: string[] | null;
        };
        /** PresetCatalog */
        PresetCatalog: {
            /** Groups */
            groups: components["schemas"]["PresetGroup"][];
            /** Presets */
            presets: components["schemas"]["Preset"][];
        };
        /** PresetGroup */
        PresetGroup: {
            /** Key */
            key: string;
            /** Label */
            label: string;
        };
        /** PreviewRequest */
        PreviewRequest: {
            /** Native File Id */
            native_file_id: string;
            /** Target File Id */
            target_file_id: string;
            /** Target Lang Code */
            target_lang_code: string;
            /** Timestamp Seconds */
            timestamp_seconds: number;
            styles: components["schemas"]["StyleConfig"];
            /**
             * @default {
             *       "bottom_ms": 0,
             *       "top_ms": 0
             *     }
             */
            offsets: components["schemas"]["TimingOffsets"];
            /**
             * @default {
             *       "width": 1920,
             *       "height": 1080
             *     }
             */
            source_resolution: components["schemas"]["Resolution"];
            /**
             * Preview Mode
             * @default ass
             */
            preview_mode: string;
            /** Video File Id */
            video_file_id?: string | null;
        };
        /** PreviewResponse */
        PreviewResponse: {
            /** Html */
            html: string;
            /** Native Text */
            native_text: string;
            /** Target Text */
            target_text: string;
            /** Romanized Text */
            romanized_text: string;
        };
        /** RegisterPathRequest */
        RegisterPathRequest: {
            /** Path */
            path: string;
        };
        /** Resolution */
        Resolution: {
            /**
             * Width
             * @default 1920
             */
            width: number;
            /**
             * Height
             * @default 1080
             */
            height: number;
        };
        /**
         * RomanizeBatchItem
         * @description One result entry — just the romanized string.  Per-call
         *     metadata (lang_code, romanization_name, has_phonetic_layer) is
         *     constant across the batch and lives at the response root.
         */
        RomanizeBatchItem: {
            /** Romanized */
            romanized: string;
        };
        /** RomanizeBatchRequest */
        RomanizeBatchRequest: {
            /**
             * Texts
             * @description UTF-8 source texts to romanize.  All texts share the lang/phonetic_system/long_vowel_mode specified at the request level.  Hard caps: ≤2000 entries, each ≤5000 chars.
             */
            texts: string[];
            /**
             * Lang Code
             * @description See POST /romanize.
             */
            lang_code: string;
            /**
             * Phonetic System
             * @description See POST /romanize.
             */
            phonetic_system?: string | null;
            /**
             * Long Vowel Mode
             * @description See POST /romanize.
             * @default macrons
             */
            long_vowel_mode: string;
            /**
             * Opt In Training
             * @description See POST /romanize.
             * @default false
             */
            opt_in_training: boolean;
        };
        /** RomanizeBatchResponse */
        RomanizeBatchResponse: {
            /**
             * Results
             * @description One entry per input text, same order as the request.  Empty/oversized texts and unsupported languages produce {romanized: ''} instead of being dropped, so positional alignment with the request is preserved.
             */
            results: components["schemas"]["RomanizeBatchItem"][];
            /** Lang Code */
            lang_code: string;
            /** Romanization Name */
            romanization_name: string;
            /** Has Phonetic Layer */
            has_phonetic_layer: boolean;
        };
        /** RomanizeRequest */
        RomanizeRequest: {
            /**
             * Text
             * @description UTF-8 source text to romanize (≤5000 chars).
             */
            text: string;
            /**
             * Lang Code
             * @description BCP-47 language tag (ja, zh-Hans, zh-Hant, yue, ko, th, ru, hi, he, ar, fa, ur, ...).
             */
            lang_code: string;
            /**
             * Phonetic System
             * @description Per-language phonetic-system override.  Thai: paiboon|rtgs|ipa.  Arabic: learner|din|loose.  Persian: learner|dmg.  Urdu: learner|ala-lc.  Chinese: pinyin|zhuyin|jyutping (typically auto-derived from lang_code).  When omitted, falls back to the language's default.
             */
            phonetic_system?: string | null;
            /**
             * Long Vowel Mode
             * @description Japanese-only.  One of macrons|doubled|unmarked.  Ignored for other languages.
             * @default macrons
             */
            long_vowel_mode: string;
            /**
             * Opt In Training
             * @description When true, the (text, lang, romanized) tuple may be archived for OCR training data (Step 5+).  No-op until the pipeline lands.
             * @default false
             */
            opt_in_training: boolean;
        };
        /** RomanizeResponse */
        RomanizeResponse: {
            /** Romanized */
            romanized: string;
            /** Lang Code */
            lang_code: string;
            /** Romanization Name */
            romanization_name: string;
            /** Has Phonetic Layer */
            has_phonetic_layer: boolean;
        };
        /** RomanizedLayerStyle */
        RomanizedLayerStyle: {
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Fontname
             * @default Times New Roman
             */
            fontname: string;
            /**
             * Fontsize
             * @default 30
             */
            fontsize: number;
            /**
             * Bold
             * @default false
             */
            bold: boolean;
            /**
             * Italic
             * @default true
             */
            italic: boolean;
            /**
             * Primarycolor
             * @default #FFFFFF
             */
            primarycolor: string;
            /**
             * Primary Opacity
             * @default 100
             */
            primary_opacity: number;
            /**
             * Outlinecolor
             * @default #000000
             */
            outlinecolor: string;
            /**
             * Outline Opacity
             * @default 100
             */
            outline_opacity: number;
            /**
             * Backcolor
             * @default #000000
             */
            backcolor: string;
            /**
             * Back Opacity
             * @default 0
             */
            back_opacity: number;
            /**
             * Outline Enabled
             * @default true
             */
            outline_enabled: boolean;
            /**
             * Outline
             * @default 1.5
             */
            outline: number;
            /**
             * Shadow Enabled
             * @default false
             */
            shadow_enabled: boolean;
            /**
             * Shadow
             * @default 1.5
             */
            shadow: number;
            /**
             * Background Enabled
             * @default false
             */
            background_enabled: boolean;
            /**
             * Glow Enabled
             * @default false
             */
            glow_enabled: boolean;
            /**
             * Glow Radius
             * @default 5
             */
            glow_radius: number;
            /**
             * Glow Color Hex
             * @default #FFFF00
             */
            glow_color_hex: string;
            /**
             * Alignment
             * @default 8
             */
            alignment: number;
            /**
             * Marginl
             * @default 10
             */
            marginl: number;
            /**
             * Marginr
             * @default 10
             */
            marginr: number;
            /**
             * Marginv
             * @default 10
             */
            marginv: number;
            /**
             * Long Vowel Mode
             * @default macrons
             * @enum {string}
             */
            long_vowel_mode: "macrons" | "doubled" | "unmarked";
        };
        /** ScanRequest */
        ScanRequest: {
            /** File Id */
            file_id: string;
        };
        /** ScanResponse */
        ScanResponse: {
            metadata: components["schemas"]["VideoMetadata"];
            /** Tracks */
            tracks: components["schemas"]["TrackInfo"][];
            /**
             * Audio Tracks
             * @default []
             */
            audio_tracks: components["schemas"]["AudioTrackInfo"][];
        };
        /**
         * StyleConfig
         * @description The full styles dict the engine consumes.
         *
         *     Mirrors the hybrid shape used in the codebase: layer dicts keyed by
         *     ``"Bottom"``/``"Top"``/``"Romanized"``/``"Annotation"`` plus a few
         *     top-level scalars. Field aliases preserve the layer-name casing so a
         *     JSON payload can use either the alias (``{"Bottom": {...}}``) or the
         *     snake_case attribute (``{"bottom": {...}}``).
         */
        StyleConfig: {
            Bottom?: components["schemas"]["BottomLayerStyle"];
            Top?: components["schemas"]["TopLayerStyle"];
            Romanized?: components["schemas"]["RomanizedLayerStyle"];
            Annotation?: components["schemas"]["AnnotationLayerStyle"];
            /**
             * Vertical Offset
             * @default 0
             */
            vertical_offset: number;
            /**
             * Annotation Gap
             * @default 2
             */
            annotation_gap: number;
            /**
             * Romanized Gap
             * @default 0
             */
            romanized_gap: number;
            /** Script Display */
            script_display?: ("original" | "simplified" | "traditional") | null;
        };
        /**
         * StyleInfo
         * @description Per-style metadata from ``subs/processing.detect_ass_styles``.
         *
         *     Wire-safe — drops the engine's nested ``style: SSAStyle`` field which
         *     can't cross JSON.
         */
        StyleInfo: {
            /** Name */
            name: string;
            /** Event Count */
            event_count: number;
            /** Has Animation */
            has_animation: boolean;
            /**
             * Role
             * @enum {string}
             */
            role: "dialogue" | "preserve" | "exclude";
            /**
             * Sample Text
             * @default
             */
            sample_text: string;
        };
        /**
         * SuggestFilenameRequest
         * @description Request a sanitized, metadata-aware default filename for a Save
         *     dialog. All inputs are optional — missing fields just get skipped.
         *
         *     Mirrors the Streamlit flow (loom_app.py:1252): pulls media title +
         *     year from the video (when a ``video_file_id`` is supplied) and folds
         *     in the native/target language codes plus annotation / romanization
         *     system names.
         */
        SuggestFilenameRequest: {
            /** Ext */
            ext: string;
            /** Video File Id */
            video_file_id?: string | null;
            /** Native Lang Code */
            native_lang_code?: string | null;
            /** Target Lang Code */
            target_lang_code?: string | null;
            /** Phonetic System */
            phonetic_system?: string | null;
            /**
             * Include Annotations
             * @default false
             */
            include_annotations: boolean;
            /**
             * Include Romanization
             * @default true
             */
            include_romanization: boolean;
        };
        /** SuggestFilenameResponse */
        SuggestFilenameResponse: {
            /** Filename */
            filename: string;
        };
        /** TimingOffsets */
        TimingOffsets: {
            /**
             * Bottom Ms
             * @default 0
             */
            bottom_ms: number;
            /**
             * Top Ms
             * @default 0
             */
            top_ms: number;
        };
        /** TopLayerStyle */
        TopLayerStyle: {
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Fontname
             * @default Noto Sans
             */
            fontname: string;
            /**
             * Fontsize
             * @default 52
             */
            fontsize: number;
            /**
             * Bold
             * @default false
             */
            bold: boolean;
            /**
             * Italic
             * @default false
             */
            italic: boolean;
            /**
             * Primarycolor
             * @default #FFFFFF
             */
            primarycolor: string;
            /**
             * Primary Opacity
             * @default 100
             */
            primary_opacity: number;
            /**
             * Outlinecolor
             * @default #000000
             */
            outlinecolor: string;
            /**
             * Outline Opacity
             * @default 100
             */
            outline_opacity: number;
            /**
             * Backcolor
             * @default #000000
             */
            backcolor: string;
            /**
             * Back Opacity
             * @default 0
             */
            back_opacity: number;
            /**
             * Outline Enabled
             * @default true
             */
            outline_enabled: boolean;
            /**
             * Outline
             * @default 2.5
             */
            outline: number;
            /**
             * Shadow Enabled
             * @default false
             */
            shadow_enabled: boolean;
            /**
             * Shadow
             * @default 1.5
             */
            shadow: number;
            /**
             * Background Enabled
             * @default false
             */
            background_enabled: boolean;
            /**
             * Glow Enabled
             * @default false
             */
            glow_enabled: boolean;
            /**
             * Glow Radius
             * @default 5
             */
            glow_radius: number;
            /**
             * Glow Color Hex
             * @default #FFFF00
             */
            glow_color_hex: string;
            /**
             * Alignment
             * @default 8
             */
            alignment: number;
            /**
             * Marginl
             * @default 10
             */
            marginl: number;
            /**
             * Marginr
             * @default 10
             */
            marginr: number;
            /**
             * Marginv
             * @default 90
             */
            marginv: number;
        };
        /**
         * TrackInfo
         * @description One subtitle track surfaced to the UI.
         *
         *     Wire-safe view of the dict returned by
         *     ``video/mkv_handler.scan_and_extract_tracks``. The engine returns ``path``
         *     (a server-side filesystem path); the API route registers that path with
         *     storage and exposes ``file_id`` instead so clients can reference the
         *     extracted track in subsequent requests. Image-based tracks (PGS, VobSub)
         *     carry ``selectable=False`` and ``file_id=None``.
         */
        TrackInfo: {
            /** Id */
            id: number;
            /** Sub Num */
            sub_num?: number | null;
            /** Label */
            label: string;
            /** File Id */
            file_id?: string | null;
            /** Lang Code */
            lang_code?: string | null;
            /**
             * Source
             * @default mkv
             * @enum {string}
             */
            source: "mkv" | "external";
            /**
             * Selectable
             * @default true
             */
            selectable: boolean;
            /** Codec */
            codec?: string | null;
            /** Metadata Lang */
            metadata_lang?: string | null;
            /** Track Title */
            track_title?: string | null;
        };
        /** UploadResponse */
        UploadResponse: {
            /** Id */
            id: string;
            /** Filename */
            filename: string;
            /** Size */
            size: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VideoMetadata */
        VideoMetadata: {
            /** Title */
            title?: string | null;
            /** Year */
            year?: number | null;
            /**
             * Duration Seconds
             * @default 0
             */
            duration_seconds: number;
            /**
             * Width
             * @default 1920
             */
            width: number;
            /**
             * Height
             * @default 1080
             */
            height: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    upload_file_files_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_file_files_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_file_by_path_files_by_path_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterPathRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_file_files__file_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    language_config_language_config__code__get: {
        parameters: {
            query?: {
                phonetic_system?: string | null;
            };
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LanguageMetadata"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    romanize_romanize_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RomanizeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RomanizeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    romanize_batch_romanize_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RomanizeBatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RomanizeBatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    annotate_annotate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnnotateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnnotateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    annotate_batch_annotate_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnnotateBatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnnotateBatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_ass_generate_ass_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateAssRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateAssResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_pgs_generate_pgs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GeneratePgsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    suggest_filename_generate_suggest_filename_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SuggestFilenameRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestFilenameResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_video_video_scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detect_subtitle_language_subs_detect_language_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FileIdRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetectLanguageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detect_subtitle_styles_subs_detect_styles_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FileIdRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetectStylesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compute_align_align_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlignRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlignResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    render_preview_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fonts_styles_fonts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FontList"];
                };
            };
        };
    };
    presets_styles_presets_get: {
        parameters: {
            query?: {
                lang?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresetCatalog"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_mux_mux_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MuxRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    corpus_capture_corpus_capture_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CorpusCaptureRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorpusCaptureResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    define_capabilities_define_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefineCapabilities"];
                };
            };
        };
    };
    define_batch_define_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DefineRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefineResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
